variables:
  QUARTO_VERSION: "1.3.450"

pages:
  stage: deploy
  image: ubuntu:22.04
  before_script:
    - apt-get update
    - apt-get install -y wget
    - wget "https://github.com/quarto-dev/quarto-cli/releases/download/v${QUARTO_VERSION}/quarto-${QUARTO_VERSION}-linux-amd64.deb"
    - apt-get install "./quarto-${QUARTO_VERSION}-linux-amd64.deb"
  script:
    - quarto render --output-dir public
    - if [ -e "index-speaker.html" ]; then mv index-speaker.html public; fi
  artifacts:
    paths: 
    - public/
